#!python

"""
        COPYRIGHT (c) 2019-2023 by Featuremine Corporation.
        
        This Source Code Form is subject to the terms of the Mozilla Public
        License, v. 2.0. If a copy of the MPL was not distributed with this
        file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""

import unittest
import importlib
import sys


tests_module = "@TESTS_PACKAGE@"

if __name__ == '__main__':
    mod = importlib.import_module(tests_module if len(sys.argv) <= 1 else f"{tests_module}.{sys.argv[1]}")
    dir = mod.__path__[0]
    testsuite = unittest.defaultTestLoader.discover(start_dir=dir, pattern='*.py')
    assert unittest.TextTestRunner(verbosity=2,failfast=True).run(testsuite).wasSuccessful(), 'Test runner failed'
